### ISSUE TITLE
Interaction with objects

### ISSUE THREAD

**Issue by GuillemBarroso** [GuillemBarroso/CLing#27]
The user should be able to interact with different objects in the game. 

For instance, it should be possible to ``look at wall``. And then, a message should be returned with some information:

>You see a rock solid wall.

This implies that some objects should be able to be looked at, searched, forced, etc. An object should be created to deal with these interactions.

Also, some work will be required to check which is the closest object to the player. So, for instance, if there are several walls in a room, the player will ``look at`` the closest wall to him. A maximum distance will be defined in which the player can interact with objects. Then, within that distance, the player will interact with the closest object.

**Comment by GuillemBarroso** [comment]
Yes @akaszynski! I remember you demonstrating how GPT could create these sequences.  

I can clearly see the trivial approach; using GPT to create room descriptions, NPC conversations, interaction with objects, ... and then copy-pasting (hardcoding) the text in the game.  This would save time when creating all these texts.

However, I find it hard to see how could I add anything that is dynamically changing, since I would have to adapt the graphical interface accordingly. 

Thanks for the suggestion!

**Comment by akaszynski** [comment]
> However, I find it hard to see how could I add anything that is dynamically changing, since I would have to adapt the graphical interface accordingly.

Indeed, though you could make a dungeon generator so the entire project is dynamic. This would change this game from being static to "rogue-like". GPT enabled rogue-like would be pretty crazy.

**Comment by GuillemBarroso** [comment]
Yep, agree.

Using chat.openai: 

![image](https://user-images.githubusercontent.com/53979143/216039387-9db721e1-8988-4df9-b6cb-3707e5afc928.png)

Since chat.openai remembers all the previous conversations, it would be quite easy to write the entire game lore.
